name: octras
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.2
  - attrs=20.3.0
  - blas=1.0
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - cffi=1.14.4
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - iniconfig=1.1.1
  - intel-openmp=2020.2
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=9.1.0
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - more-itertools=8.6.0
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1i
  - packaging=20.8
  - pandas=1.1.5
  - pip=20.3.3
  - pluggy=0.13.1
  - py=1.10.0
  - pycparser=2.20
  - pyparsing=2.4.7
  - pytest=6.2.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytorch=1.4.0
  - pytz=2020.4
  - readline=8.0
  - scipy=1.5.2
  - setuptools=51.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.1
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - deep-merge==0.0.4
    - deepmerge==0.1.1
