simulation_path: /home/shoerl/bo
working_directory: /home/shoerl/bo/work

simulation:
  sample_size: 1pm # Default sample size of the simulation: 1pm, 1pct, 10pct, 25pct
  number_of_threads: 4 # Number of threads in one simulation
  iterations: 40 # Default number of iterations for one simulation
  memory: 10G # May need to be increased for large sample sizes

calibration:
  decision_variables: all # May be "constants", "vots", or "all"
  problem: mode_share_by_distance # May be "total_mode_share", "car_travel_time", "mode_share_by_distance"
  objective: hellinger # May be "hellinger" or "l2"
  reference_sample_size: 1pm # Reference sample size, should be high, e.g. 25pct
  output_path: /home/shoerl/bo/work/output2.p # Calibration output path

scheduler:
  number_of_runners: 1 # How many simulations should be allowed to run in parallel? (Consider memory and threads!)
  ping_time: 1.0 # Defines how often to update the simulation state.

# Example 1: Using SPSA
#optimization:
#  algorithm: spsa
#  perturbation_factor: 0.2
#  gradient_factor: 1.0

# Example 2: Using Bayesian Optimization
optimization:
  algorithm: bo
  method: mes
  batch_size: 4
  initial_samples: 4

#
